# Jekyll Configuration for Telco-Sec-Documentation
# GitHub Pages site configuration - SEO Optimized

# Site settings
title: "Telco Security Research Documentation"
description: "Comprehensive telecom security research documents, white papers, standards, and best practices organized by category with advanced search functionality"
url: "https://telcosec.github.io"
baseurl: "/Telco-Sec-Documentation"

# Author information
author:
  name: "Telco Security Community"
  email: "contact@telcosec.org"
  bio: "Telecom security professionals and researchers sharing knowledge and best practices"
  location: "Global"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TelcoSec"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/company/telcosec"

# SEO and Meta settings
lang: "en"
locale: "en_US"
timezone: "UTC"
encoding: "utf-8"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
relative_links:
  enabled: true
  collections: true

# SEO Plugin Configuration
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# SEO Tag Defaults
seo:
  title: "Telco Security Research Documentation"
  description: "Comprehensive telecom security research documents, white papers, standards, and best practices organized by category with advanced search functionality"
  author: "Telco Security Community"
  image: "/assets/images/telco-security-og.jpg"
  image_alt: "Telco Security Research Documentation Hub"
  twitter:
    creator: "@telcosec"
    site: "@telcosec"
  facebook:
    app_id: "123456789"
  google_analytics: "G-XXXXXXXXXX"
  google_verification: "your-google-verification-code"
  bing_verification: "your-bing-verification-code"
  yandex_verification: "your-yandex-verification-code"

# Collections
collections:
  documents:
    output: true
    permalink: /:collection/:name/
    sort_by: date
    reverse: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "documents"
    values:
      layout: "document"
      author: "Telco Security Community"
      comments: true
      share: true
      related: true

# Pagination
paginate: 20
paginate_path: "/page/:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-category
    tag: archive-tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Search
search: true
search_full_content: true
search_exclude:
  - "assets/"
  - "_site/"
  - "node_modules/"

# Categories with enhanced SEO
categories:
  - name: "Network Security"
    description: "Core network protection, firewalls, intrusion detection systems, and network security best practices"
    icon: "fas fa-shield-alt"
    keywords: ["network security", "firewall", "intrusion detection", "network protection", "cybersecurity"]
  - name: "5G Security"
    description: "5G network security, vulnerabilities, threats, and mitigation strategies for telecom operators"
    icon: "fas fa-broadcast-tower"
    keywords: ["5G security", "5G networks", "telecom security", "network vulnerabilities", "5G threats"]
  - name: "IoT Security"
    description: "Internet of Things security in telecom environments, device protection, and IoT threat mitigation"
    icon: "fas fa-microchip"
    keywords: ["IoT security", "device security", "telecom IoT", "connected devices", "IoT threats"]
  - name: "Cloud Security"
    description: "Cloud infrastructure security for telecom services, multi-cloud security, and cloud-native protection"
    icon: "fas fa-cloud"
    keywords: ["cloud security", "multi-cloud", "cloud-native", "telecom cloud", "infrastructure security"]
  - name: "Compliance & Standards"
    description: "Regulatory requirements, industry standards, and compliance frameworks for telecom security"
    icon: "fas fa-clipboard-check"
    keywords: ["compliance", "standards", "regulations", "frameworks", "telecom compliance"]
  - name: "Incident Response"
    description: "Security incident handling, recovery procedures, and incident management best practices"
    icon: "fas fa-exclamation-triangle"
    keywords: ["incident response", "security incidents", "recovery", "incident management", "breach response"]
  - name: "Threat Intelligence"
    description: "Current threats, attack vectors, threat hunting, and intelligence sharing in telecom security"
    icon: "fas fa-eye"
    keywords: ["threat intelligence", "threat hunting", "attack vectors", "intelligence sharing", "threat analysis"]
  - name: "Vendor Security"
    description: "Security assessments of telecom equipment, software, and third-party vendor security"
    icon: "fas fa-building"
    keywords: ["vendor security", "third-party security", "equipment security", "software security", "supply chain"]
  - name: "Physical Security"
    description: "Physical infrastructure protection, facility security, and environmental security measures"
    icon: "fas fa-hard-hat"
    keywords: ["physical security", "infrastructure protection", "facility security", "environmental security", "access control"]
  - name: "Data Protection"
    description: "Data privacy, encryption, data loss prevention, and regulatory compliance for telecom data"
    icon: "fas fa-database"
    keywords: ["data protection", "privacy", "encryption", "data loss prevention", "GDPR", "compliance"]
  - name: "Identity & Access Management"
    description: "User authentication, authorization, identity verification, and access control systems"
    icon: "fas fa-user-shield"
    keywords: ["IAM", "authentication", "authorization", "identity management", "access control", "MFA"]
  - name: "Application Security"
    description: "Secure software development, application testing, and vulnerability management for telecom apps"
    icon: "fas fa-code"
    keywords: ["application security", "secure development", "vulnerability management", "penetration testing", "code review"]
  - name: "Wireless Security"
    description: "WiFi security, Bluetooth security, and wireless communication protection in telecom environments"
    icon: "fas fa-wifi"
    keywords: ["wireless security", "WiFi security", "Bluetooth security", "radio security", "spectrum protection"]
  - name: "Satellite Security"
    description: "Satellite communication security, space-based infrastructure protection, and orbital security"
    icon: "fas fa-satellite"
    keywords: ["satellite security", "space security", "orbital security", "satellite communications", "space infrastructure"]
  - name: "Critical Infrastructure"
    description: "Protection of critical telecom infrastructure, national security considerations, and resilience planning"
    icon: "fas fa-industry"
    keywords: ["critical infrastructure", "national security", "resilience", "infrastructure protection", "emergency response"]
  - name: "Forensics & Investigation"
    description: "Digital forensics, incident investigation, evidence collection, and legal compliance in telecom security"
    icon: "fas fa-search"
    keywords: ["digital forensics", "incident investigation", "evidence collection", "legal compliance", "chain of custody"]
  - name: "Security Operations"
    description: "Security operations center (SOC) management, monitoring, and operational security procedures"
    icon: "fas fa-desktop"
    keywords: ["SOC", "security operations", "monitoring", "alert management", "security procedures"]
  - name: "Risk Management"
    description: "Security risk assessment, risk mitigation strategies, and enterprise risk management frameworks"
    icon: "fas fa-chart-line"
    keywords: ["risk management", "risk assessment", "risk mitigation", "enterprise risk", "security risk"]
  - name: "Business Continuity"
    description: "Disaster recovery planning, business continuity management, and resilience strategies for telecom services"
    icon: "fas fa-sync"
    keywords: ["business continuity", "disaster recovery", "resilience", "BCM", "DR planning"]
  - name: "Training & Awareness"
    description: "Security training programs, awareness campaigns, and human factor security in telecom organizations"
    icon: "fas fa-graduation-cap"
    keywords: ["security training", "awareness", "human factors", "security culture", "training programs"]
  - name: "Emerging Technologies"
    description: "Security considerations for AI, quantum computing, blockchain, and other emerging technologies in telecom"
    icon: "fas fa-rocket"
    keywords: ["emerging technologies", "AI security", "quantum security", "blockchain security", "future security"]

# Exclude from processing
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
  - ".bundle"
  - ".git"
  - ".github"
  - "README.md"
  - "SETUP.md"
  - "DEPLOYMENT.md"
  - "PROJECT_SUMMARY.md"
  - "CONTRIBUTING.md"

# Include for processing
include:
  - "_pages"
  - "assets"
  - "docs"

# Feed settings
feed:
  path: feed.xml
  limit: 20

# Sitemap settings
sitemap:
  changefreq: weekly
  priority: 0.8
  lastmod: true
  exclude:
    - "/feed.xml"
    - "/404.html"

# Social media and sharing
social:
  name: "Telco Security Research Documentation"
  links:
    - "https://github.com/TelcoSec"
    - "https://linkedin.com/company/telcosec"
    - "https://twitter.com/telcosec"

# Analytics and tracking
analytics:
  google: "G-XXXXXXXXXX"
  google_tag_manager: "GTM-XXXXXXX"
  facebook_pixel: "123456789"
  linkedin_insight: "123456789"

# Performance optimization
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

# Security headers
security_headers:
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  X-XSS-Protection: "1; mode=block"
  Referrer-Policy: strict-origin-when-cross-origin
  Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; connect-src 'self' https:; frame-ancestors 'none';"
