# Jekyll Configuration for Telco-Sec-Documentation
# GitHub Pages site configuration

# Site settings
title: "Telco Security Research Documentation"
description: "Comprehensive telecom security research documents organized by category with search functionality"
url: "https://yourusername.github.io"
baseurl: "/Telco-Sec-Documentation"

# Author information
author:
  name: "Telco Security Community"
  email: "contact@example.com"
  bio: "Telecom security professionals and researchers"
  location: "Global"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yourusername"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
relative_links:
  enabled: true
  collections: true

# Collections
collections:
  documents:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "documents"
    values:
      layout: "document"
      author: "Telco Security Community"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Pagination
paginate: 20
paginate_path: "/page/:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-category
    tag: archive-tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Search
search: true
search_full_content: true

# Categories
categories:
  - name: "Network Security"
    description: "Core network protection, firewalls, intrusion detection"
    icon: "fas fa-shield-alt"
  - name: "5G Security"
    description: "5G network security, vulnerabilities, and mitigations"
    icon: "fas fa-broadcast-tower"
  - name: "IoT Security"
    description: "Internet of Things security in telecom environments"
    icon: "fas fa-microchip"
  - name: "Cloud Security"
    description: "Cloud infrastructure security for telecom services"
    icon: "fas fa-cloud"
  - name: "Compliance & Standards"
    description: "Regulatory requirements and industry standards"
    icon: "fas fa-clipboard-check"
  - name: "Incident Response"
    description: "Security incident handling and recovery procedures"
    icon: "fas fa-exclamation-triangle"
  - name: "Threat Intelligence"
    description: "Current threats and attack vectors"
    icon: "fas fa-eye"
  - name: "Vendor Security"
    description: "Security assessments of telecom equipment and software"
    icon: "fas fa-building"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - CONTRIBUTING.md
  - LICENSE

# Include in processing
include:
  - _pages
  - _posts
  - _drafts

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Timezone
timezone: UTC

# Encoding
encoding: utf-8

# Future posts
future: false

# Show drafts
show_drafts: false

# Limit posts
limit_posts: 0

# Excerpt separator
excerpt_separator: "\n\n"

# Incremental build
incremental: false

# Keep files
keep_files:
  - .git
  - .github
  - assets
  - _config.yml

# Ignore files
ignore:
  - .git
  - .github
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
